# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'aws-for-terraform'
    backendAWSBucketName: 'terraform-backend-state-jlq'
    backendAWSKey: 'kubernetes-dev.tfstate'
- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'validate'
- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'apply'
    environmentServiceNameAWS: 'aws-for-terraform'
- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'destroy'
    environmentServiceNameAWS: 'aws-for-terraform'