apiVersion: apps/v1
kind: Deployment
metadata:
  name: testangular-deployment
  labels:
    app: testangular
  namespace: default
spec:
  replicas: 2 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: testangular
  strategy:
    rollingUpdate:
      maxSurge: 25% 
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: testangular
    spec:
      containers:
      - name: testangular-container
        image: 746662389335.dkr.ecr.us-east-1.amazonaws.com/angulartest:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: testangular
  name: testangular-service
  namespace: default
spec:
  ports:
    port: 80 #CHANGE
    protocol: TCP
    targetPort: 8000 #CHANGE
  selector:
    app: testangular
  sessionAffinity: None #CHANGE
  type: LoadBalancer