apiVersion: apps/v1
kind: Deployment
metadata:
  name: testangular-deployment
  labels:
    app: testangular
  namespace: default
spec:
  replicas: 2 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: testangular
  strategy:
    rollingUpdate:
      maxSurge: 25% 
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: testangular
    spec:
      containers:
      - name: testangular-container
        image: 746662389335.dkr.ecr.us-east-1.amazonaws.com/angulartest:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: liveness-port
          containerPort: 8000
        resources: #CHANGE
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi #256Mi 
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: testangular
  name: testangular-service
  namespace: default
spec:
  ports:
  - # nodePort: 30702 #CHANGE
    port: 80 #CHANGE
    protocol: TCP
    targetPort: 8000 #CHANGE
  selector:
    app: testangular
  sessionAffinity: None #CHANGE
  type: LoadBalancer